#!/usr/bin/python3
import argparse
from gistright import add, clone, ls, mk, new, push, quick, rm, show, status

commands = {
    'add': add,
    'clone': clone,
    'ls': ls,
    'mk': mk,
    'new': new,
    'push': push,
    'quick': quick,
    'rm': rm,
    'show': show,
    'status': status,
}

class Gist():

    def __init__(self):
        parser = argparse.ArgumentParser(
            description='A \'git\'-like tool for gists',
        )

        command_parsers = parser.add_subparsers(
            title='command',
            dest='command',
            metavar='command',
            help='Selects between different operations',
        )
        command_parsers.required = True

        for name, cmd in commands.items():
            cmd.add_parser(command_parsers)

        args = parser.parse_args()
        commands[args.command].run(args)

Gist()
